config/routes.rb
Rails.application.routes.draw do

  resources :books do
    collection do
      get :test_nil
    end
  end
  resources :users do
    member do
      post :login
    end
    collection do
      get :logout
    end
  end
  resources :articles do
    collection do
      post :check
      post :check_erb
      post :check_file
      post :test_stream_partial
      post :test_stream_partials
      post :test_no_stream
    end
  end

  get 'channel/redirect'
  get 'channel/redirect1'
  post 'channel/redirect1'
  get 'channel/redirect2'
  get 'channel/redirect3'
  post 'channel/redirect2'
  post 'channel/flash_test'
  post 'channel/make_red'
  post 'channel/make_red_to_me'
  post 'channel/make_red_to_authenticated_group'
  post 'channel/make_green'
  post 'channel/partial_locals_test'
  post 'channel/partial_to_all'
  post 'channel/template_to_all'
  post 'channel/template_to_me'
  post 'channel/template_to_authenticated_group'
  post 'channel/cable_template'
  post 'channel/multiple_to_all'
  post 'channel/class_method'

  post 'partials/test_stream_partial'
  post 'partials/test_channel'
  post 'partials/stream_by_params'
  post 'partials/channel_by_params'
  get 'partials/index'
  get 'partials/traditional'
  get 'partials/traditional2'

  resources :turbo_power do
    collection do
      post :action
    end
  end
  resources :cars do
    collection do
      get :page
    end
  end

  post 'svelte/push'
  get 'svelte/push'
  post 'svelte/push2'
  get 'svelte', to: 'svelte#index'

  root "articles#index"
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
    # testmethod
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    turbo_stream_save(
      @article.save,
      if_success_turbo_redirect_to: ->{article_path(@article)},
      target_id: 'form',
      partial: 'form'
    )
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    turbo_stream_save(
      @article.update(article_params),
      if_success_turbo_redirect_to: (params['no_redirection'] == 'true' ? nil : articles_path),
      target_id: 'form',
      partial: 'form'
    )
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    turbo_stream_save(
      @article.destroy,
      if_success_redirect_to: articles_path
    )
  end

  def check
    render layout: false
  end

  def check_erb
    render layout: false
  end

  def check_file
    p = Rails.root.join('app', 'test_outside_views', 'check_file.turbo_stream.erb')
    raise "path not working: «#{p}»" unless File.exist?(p)
    respond_to do |format|
      format.turbo_stream { render file: p, layout: false }
    end
  end

  def test_stream_partials
    ary_js = params.permit(:partials_array)[:partials_array]
    if ary_js.present?
      ary = JSON.parse(ary_js)
    else
      ary = [
        {
          target_id: 'flash-box',
          partial: 'flash_box_append',
          locals: { content: "FIRST streamed partial #{SecureRandom.hex(3)}" },
          action: :append
        },
        {
          target: '#flash-box',
          partial: 'flash_box_append',
          locals: { content: "SECOND streamed partial #{SecureRandom.hex(3)}" },
          action: :append
        }
      ]
    end
    render_turbo_stream(
      ary
    )
  end

  def test_no_stream
    @article = Article.new(article_params)

    turbo_stream_save(
      @article.save,
      target_id: nil
    )
    redirect_to root_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper



end

app/views/articles/_flash_box.haml
#flash-box
  %div
    = content

app/views/articles/_flash_box_append.haml
-# in Case of APPEND / PREPEND the ID Tag (#flash-box) is not provided from the partial


%div
  = content

app/views/articles/_form.html.haml
= turbo_frame_tag 'form' do
  = form_for @article do |f|
    = SecureRandom.hex(3)
    .field
      = f.label :title
      = f.text_field :title
    .field
      = f.label :description
      = f.text_area :description
    .actions
      = f.submit 'Save'

app/views/articles/check.turbo_stream.haml
= turbo_stream.replace 'flash-box' do
  #flash-box
    = content_tag :td, 'turbo-stream.haml is working!'

app/views/articles/check_erb.turbo_stream.erb
<%= turbo_stream.replace 'flash-box' do %>
  <%= content_tag :div, 'turbo-stream.erb is working!', id: 'flash-box' %>
<% end %>

app/views/articles/create.turbo_stream.haml
- if @saved
  - flash[:notice] = 'Article created successfully'
  = turbo_stream.redirect_to articles_path
- else
  - flash.now[:alert] = 'Article could not be created'
  = turbo_stream.replace 'article-form' do
    = render 'form'
  = turbo_stream.prepend 'flash-box' do
    = render 'layouts/flash'

app/views/articles/edit.html.haml
%h1= "Editing article #{@article.title}"


= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1 Listing articles

%p
  Redirection here is handled by "turbo_redirect_to", which is
  %strong
    after successful update/creation,
  uses the redirect_to from #{link_to 'marcoroths turbo_power', 'https://github.com/marcoroth/turbo_power'} gem. This will break out of all frames!
  The flash notice is set in the traditional way like "flash[:notice] = ..." and retrieved when the layout renders.

%table
  %thead
    %tr
      %th Title
      %th Description
      %th
      %th
      %th

  %tbody
    - @articles.all.each do |article|
      %tr{ id: "article-#{article.id}", class: (article == last_saved_object ? 'is-last-saved-object' : nil) }
        %td= article.title
        %td= article.description
        %td= link_to 'Show', article
        %td= link_to 'Edit', edit_article_path(article)
        %td= button_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }


%br

= link_to 'New Article', new_article_path

%hr
= button_to 'check turbo-stream haml', check_articles_path, method: :post
= button_to 'check turbo-stream ERB', check_erb_articles_path, method: :post
= button_to 'stream partials', test_stream_partials_articles_path, method: :post

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @article.title
%p
  %b Description:
  = @article.description

= link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Back', articles_path