config/routes.rb
Rails.application.routes.draw do

  resources :books do
    collection do
      get :test_nil
    end
  end
  resources :users do
    member do
      post :login
    end
    collection do
      get :logout
    end
  end
  resources :articles do
    collection do
      post :check
      post :check_erb
      post :check_file
      post :test_stream_partial
      post :test_stream_partials
      post :test_no_stream
    end
  end

  get 'channel/redirect'
  get 'channel/redirect1'
  post 'channel/redirect1'
  get 'channel/redirect2'
  get 'channel/redirect3'
  post 'channel/redirect2'
  post 'channel/flash_test'
  post 'channel/make_red'
  post 'channel/make_red_to_me'
  post 'channel/make_red_to_authenticated_group'
  post 'channel/make_green'
  post 'channel/partial_locals_test'
  post 'channel/partial_to_all'
  post 'channel/template_to_all'
  post 'channel/template_to_me'
  post 'channel/template_to_authenticated_group'
  post 'channel/cable_template'
  post 'channel/multiple_to_all'
  post 'channel/class_method'

  post 'partials/test_stream_partial'
  post 'partials/test_channel'
  post 'partials/stream_by_params'
  post 'partials/channel_by_params'
  get 'partials/index'
  get 'partials/traditional'
  get 'partials/traditional2'

  resources :turbo_power do
    collection do
      post :action
    end
  end
  resources :cars do
    collection do
      get :page
    end
  end

  post 'svelte/push'
  get 'svelte/push'
  post 'svelte/push2'
  get 'svelte', to: 'svelte#index'

  root "articles#index"
end

app/controllers/channel_controller.rb
class ChannelController < ApplicationController

  include FooHelper

  def redirect
    a = 1
  end

  def redirect1

  end

  def redirect2
    turbo_stream_save(
      true,
      if_success_redirect_to: channel_redirect3_path,
      object: Article.new,
      flash_controller_action_name: :create
    )
  end

  def redirect3

  end

  def flash_test
    if params['to_all']
      render_to_all(
        'flash-box',
        :prepend,
        partial: 'layouts/flash',
        locals: { 'message' => 'its working by cable-stream!' }
      )
    else
      render_to_me(
        'flash-box',
        :prepend,
        partial: 'layouts/flash',
        locals: { 'message' => 'its working by cable-stream!' }
      )
    end
    render layout: false
  end

  def make_red
    action_to_all(
      'add_css_class',
      '#colored-element',
      'background-red'
    )
    action_to_all(
      'remove_css_class',
      '#colored-element',
      'background-green'
    )
  end

  def make_red_to_me
    action_to_me(
      'add_css_class',
      '#colored-element',
      'background-red'
    )
    action_to_me(
      'remove_css_class',
      '#colored-element',
      'background-green'
    )
  end

  def make_red_to_authenticated_group
    action_to_authenticated_group(
      helpers.current_user.group,
      'add_css_class',
      '#colored-element',
      'background-red'
    )
    action_to_authenticated_group(
      helpers.current_user.group,
      'remove_css_class',
      '#colored-element',
      'background-green'
    )
  end

  def make_green
    action_to_all(
      'remove_css_class',
      '#colored-element',
      'background-red'
    )
    action_to_all(
      'add_css_class',
      '#colored-element',
      'background-green'
    )
  end

  def partial_to_all
    render_to_all(
      'render-to-box',
      partial: 'channel/cable_easy_partial',
      locals: {
        comment: 'simple partial to all users rendered'
      }
    )
  end

  def template_to_all
    render_to_all(
      'render-to-box',
      locals: {
        comment: 'rendered default template to all visitors'
      }
    )
  end

  def multiple_to_all
    render_to_all(
      'render-to-box',
    )
    render_to_all(
      'flash-box',
      :prepend,
      partial: 'layouts/flash',
      locals: { message: 'flash one from multiple to all', success: true }
    )
  end

  def template_to_me
    render_to_me(
      'render-to-box',
      locals: {
        comment: "rendered default template to me (#{helpers.current_user.name})"
      }
    )
  end

  def template_to_authenticated_group
    render_to_authenticated_group(
      helpers.current_user.group,
      'render-to-box',
      locals: {
        comment: "rendered default template to group «#{helpers.current_user.group}»"
      }
    )
  end

  def cable_template
    render_to_all(
      'template-box',
      'replace',
      locals: { greetings: 'greetings from locals' }
    )
  end

  def class_method
    channel = RenderTurboStream::Channel.new(
      :all,
      partial: 'channel/class_method_partial'
    )
    channel.send

    # for testing
    RenderTurboStream::Test::Request::Libs.set_test_responses(response, channel.test_responses)
  end

end

app/views/channel/_cable_easy_partial.haml
= turbo_frame_tag 'render-to-box' do
  %h1
    rendered!
  %p
    = SecureRandom.hex(2)
  %p
    = comment

app/views/channel/_cable_partial.haml
%div
  im rendered

app/views/channel/_class_method_partial.haml
= turbo_frame_tag 'class-method-box' do
  %h1
    Rendered from Class Method by Channel
  %p= SecureRandom.hex(3)

app/views/channel/multiple_to_all.html.haml
= turbo_frame_tag 'render-to-box' do
  %h1
    rendered one from more to all!
  %p
    = SecureRandom.hex(2)

app/views/channel/redirect.html.haml
%h1
  Turbo-Channel
- if session[:user_id]
  %p.text-green
    You are logged in as
    %strong
      %u
        = current_user.name
    group:
    %strong
      %u
        = current_user.group
- else
  %h2.text-red
    You are not logged in, so not all features will work here.
%hr
%h2
  channel_from / render_to_* methods
%p
  Please
  %strong
    open three browsers,
On 2 login with two different users from the same group and the third without login. Then click these buttons and see what happens.

- if session[:user_id]
  = button_to 'template to me', channel_template_to_me_path, method: :post
  = button_to "partial to authenticated group «#{current_user.group}»", channel_template_to_authenticated_group_path, method: :post
= button_to 'partial to all', channel_partial_to_all_path, method: :post
= button_to 'template to all', channel_template_to_all_path, method: :post
= button_to 'multiple to all', channel_multiple_to_all_path, method: :post
= button_to 'flash to me', channel_flash_test_path, method: :post
= button_to 'flash to all', channel_flash_test_path(to_all: true), method: :post

= turbo_frame_tag 'render-to-box'



%hr
%h2
  action_to_* methods
%p
  run commands from
  = link_to 'turbo_power gem', 'https://github.com/marcoroth/turbo_power'
  = button_to 'background green to all', channel_make_green_path, method: :post
  = button_to 'background red to all', channel_make_red_path, method: :post
  = button_to 'background red to me', channel_make_red_to_me_path, method: :post
  = button_to 'background red to authenticated group', channel_make_red_to_authenticated_group_path, method: :post

#colored-element


%hr
%h2
  Redirect
%p
  classic redirect from controller within a turbo-frame in parallel with sending partials by Turbo::StreamsChannel


= turbo_frame_tag 'redirect-box', src: channel_redirect1_path

%hr

%h2
  Class Methods
%p
  Doing the same like above, but with class methods instead of controller helpers
= button_to 'class method to box', channel_class_method_path
= turbo_frame_tag 'class-method-box'

app/views/channel/redirect1.html.haml
= turbo_frame_tag 'redirect-box' do
  %h1
    Redirect-1
  = button_to 'redirect and flash', channel_redirect2_path, method: :post

app/views/channel/redirect3.html.haml
= turbo_frame_tag 'redirect-box' do
  %h1
    Redirected from controller!

app/views/channel/template_to_all.html.haml
= turbo_frame_tag 'render-to-box' do
  %h1
    rendered!
  %p
    = SecureRandom.hex(2)
  %p
    = comment

app/views/channel/template_to_authenticated_group.html.haml
= turbo_frame_tag 'render-to-box' do
  %h1
    rendered!
  %p
    = SecureRandom.hex(2)
  %p
    = comment

app/views/channel/template_to_me.html.haml
= turbo_frame_tag 'render-to-box' do
  %h1
    rendered!
  %p
    = SecureRandom.hex(2)
  %p
    = comment