config/routes.rb
Rails.application.routes.draw do

  resources :books do
    collection do
      get :test_nil
    end
  end
  resources :users do
    member do
      post :login
    end
    collection do
      get :logout
    end
  end
  resources :articles do
    collection do
      post :check
      post :check_erb
      post :check_file
      post :test_stream_partial
      post :test_stream_partials
      post :test_no_stream
    end
  end

  get 'channel/redirect'
  get 'channel/redirect1'
  post 'channel/redirect1'
  get 'channel/redirect2'
  get 'channel/redirect3'
  post 'channel/redirect2'
  post 'channel/flash_test'
  post 'channel/make_red'
  post 'channel/make_red_to_me'
  post 'channel/make_red_to_authenticated_group'
  post 'channel/make_green'
  post 'channel/partial_locals_test'
  post 'channel/partial_to_all'
  post 'channel/template_to_all'
  post 'channel/template_to_me'
  post 'channel/template_to_authenticated_group'
  post 'channel/cable_template'
  post 'channel/multiple_to_all'
  post 'channel/class_method'

  post 'partials/test_stream_partial'
  post 'partials/test_channel'
  post 'partials/stream_by_params'
  post 'partials/channel_by_params'
  get 'partials/index'
  get 'partials/traditional'
  get 'partials/traditional2'

  resources :turbo_power do
    collection do
      post :action
    end
  end
  resources :cars do
    collection do
      get :page
    end
  end

  post 'svelte/push'
  get 'svelte/push'
  post 'svelte/push2'
  get 'svelte', to: 'svelte#index'

  root "articles#index"
end

app/models/car.rb
class Car < ApplicationRecord
  validates :title, presence: true
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def page

  end

  def index
    a = 1
  end

  def new
    @car = Car.new
  end

  def edit
    @car = Car.find(params['id'])
  end

  def update
    @car = Car.find(params['id'])
    turbo_stream_save(
      @car.update(car_params),
      if_success_redirect_to: cars_path,
      partial: 'form'
    )
    # target-id: turbo_stream_save fetches it from the 'form'!!
  end

  def create
    @car = Car.new(car_params)
    turbo_stream_save(
      @car.save,
      if_success_redirect_to: cars_path,
    )
  end

  def destroy
    @car = Car.find(params['id'])
    turbo_stream_save(
    @car.destroy,
    if_success_redirect_to: cars_path
    )
  end

  private

  def car_params
    params.require(:car).permit(:title, :id, :description)
  end
end

app/views/cars/_form.html.haml
= turbo_target_tag do
  = simple_form_for @car do |f|
    = f.input :title
    = f.button :submit

app/views/cars/create.html.haml
= render 'form'

app/views/cars/edit.html.haml
= turbo_frame_tag 'cars-box' do
  %h3
    edit car
  = render 'form'

app/views/cars/index.html.haml
= turbo_frame_tag 'cars-box' do
  %h1
    cars-index
  = link_to 'new', new_car_path
  %table
    %thead
      %tr
        %th
          title
        %th
    %tbody
      - Car.all.each do |c|
        %tr
          %td= c.title
          %td= link_to 'edit', edit_car_path(c)
          %td= button_to 'destroy', car_path(c), method: :delete

app/views/cars/new.html.haml
= turbo_frame_tag 'cars-box' do
  %h3
    new car
  = render 'form'

app/views/cars/page.html.haml
- unless current_user
  %h2.text-red
    You must login to see features by channel working!


%h1
  Update and create by Stream
%p
  Controller is loaded lazy (by parent frames src attribute)
%p
  Attention: The form is wrapped by div with id which is targeted by turbo-stream. If the form would be surrounded by turbo_frame the redirection of the outer turbo-frame after successful form submission would not work.
%p
  Because redirection is not possible along with turbo-stream response, Flash after successful form submission
  %strong
    is done by Channel!
  This is handled automatically by turbo_stream_save if configured to do so.
= turbo_frame_tag 'cars-box', src: cars_path

%h3
  Here are 2 additional features demonstrated:
%ul
  %li
    The controller action :update does not define a target-id! On rendering, turbo_stream_save gets it from the rendered partial, from the first turbo frame or element with the data_turbo_target attribute. This way you can define the target-id in a single place.
  %li
    There is no partial defined for the :create action! In this case turbo_stream_save uses the default template, treats it as a partial and renders it with turbo-stream, along with other partials like the flash message.

%h1
  Update and create by Channel
%p
  All Views must reside within a turbo_frame_tag with ID 'books-box'. Otherwise Turbo would not be able to handle the r  esponse.
%p
  If no
  %strong
    target_id
  argument is given to turbo_stream_save, and the config
  %strong
    allow_channel_to_me_for_turbo_stream_save
  is set to true, then the turbo_stream_save method will only
  %strong
    send the generated flash message and additional provided partials by channel,
  and will
  %strong
    not interfere the default render method
  so that the given templates (update/create) are rendered.
%p
  Create action does the minimum, update action adds a second flash and sets the element to green.

= turbo_frame_tag 'books-box', src: books_path

#colored-element