config/routes.rb
Rails.application.routes.draw do

  resources :books do
    collection do
      get :test_nil
    end
  end
  resources :users do
    member do
      post :login
    end
    collection do
      get :logout
    end
  end
  resources :articles do
    collection do
      post :check
      post :check_erb
      post :check_file
      post :test_stream_partial
      post :test_stream_partials
      post :test_no_stream
    end
  end

  get 'channel/redirect'
  get 'channel/redirect1'
  post 'channel/redirect1'
  get 'channel/redirect2'
  get 'channel/redirect3'
  post 'channel/redirect2'
  post 'channel/flash_test'
  post 'channel/make_red'
  post 'channel/make_red_to_me'
  post 'channel/make_red_to_authenticated_group'
  post 'channel/make_green'
  post 'channel/partial_locals_test'
  post 'channel/partial_to_all'
  post 'channel/template_to_all'
  post 'channel/template_to_me'
  post 'channel/template_to_authenticated_group'
  post 'channel/cable_template'
  post 'channel/multiple_to_all'
  post 'channel/class_method'

  post 'partials/test_stream_partial'
  post 'partials/test_channel'
  post 'partials/stream_by_params'
  post 'partials/channel_by_params'
  get 'partials/index'
  get 'partials/traditional'
  get 'partials/traditional2'

  resources :turbo_power do
    collection do
      post :action
    end
  end
  resources :cars do
    collection do
      get :page
    end
  end

  post 'svelte/push'
  get 'svelte/push'
  post 'svelte/push2'
  get 'svelte', to: 'svelte#index'

  root "articles#index"
end

app/views/layouts/_flash.haml
-# - message = ((locals[:message] rescue false) || local_assigns[:message])
-# - success = ((locals[:success] rescue false) || local_assigns[:success]  rescue false)
.callout{'data-closable' => true, data: { controller: 'flash', seconds: 3 }, class: ((success rescue false) ? 'success' : 'alert') }
  .text-content
    = message
  %button.close-button{'type' => 'button', 'data-close' => true }
    %span{ 'aria-hidden' => true }
      &times;

app/views/layouts/_flashes.haml
#flash-box
  - (notice.is_a?(Array) ? notice : [notice]).compact.each do |notice|
    = render 'layouts/flash', success: true, message: notice
  - (alert.is_a?(Array) ? alert : [alert]).compact.each do |alert|
    = render 'layouts/flash', success: true, message: alert

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RenderTurboStream
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application"
    = vite_stylesheet_tag 'application.scss', media: :all
    = vite_client_tag
    = vite_javascript_tag 'application'
    /

  %body
    = channel_from_me
    = channel_from_all
    = channel_from_authenticated_group(current_user&.group)
    #nav
      = link_to 'Artikel', root_path
      = link_to 'Turbo-Power', turbo_power_index_path
      = link_to 'CRUD inside frame', page_cars_path
      = link_to 'Channels', channel_redirect_path
      = link_to 'Users/Login', users_path
      = link_to 'Svelte', svelte_path
      = link_to 'Partials and variables', partials_index_path
    = render 'layouts/flashes'
    = yield

app/views/layouts/render_redirect.turbo_stream.erb
<%= turbo_stream.redirect_to local_assigns[:url] %>